# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcacfc3e4a5224f010e094b923fffb29403464c41d7c01cbd8cb1d725a895ff9ae0fa83f47f3498fffd42dbf77012600f5d959a3468ec47233c37ed234e75a23

test:
  secret_key_base: 61aea00073c7b851a298286ec4d0448fdf2717d489634f3c7b1809efbb68c91d32435b52a2ee92935abfe8779a20fa5c1de866ae17a0da442534e38288215b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
